services:
  # A Django web service
  - type: web
    name: prestige-social
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn twitter_clone.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: prestige-social-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.7

databases:
  - name: prestige-social-db
    databaseName: prestige_social
    user: prestige_social
    plan: free
